build:
  uri: https://github.com/hpehl/first-responder-demo.git
  ref: main
  contextDir: backend
  mode: s2i
  env:
      - name: MAVEN_ARGS_APPEND
        value: "-DskipTests -DfailOnMissingWebXml=false -Dquarkus.container-image.push=false"
      - name: POSTGRESQL_DRIVER_VERSION
        value: '42.5.0'
  s2i:
    featurePacks:
      - org.jboss.eap:eap-datasources-galleon-pack:7.4.0.GA-redhat-00003
    galleonLayers:
      - cloud-server
      - postgresql-datasource
      - microprofile-reactive-messaging-kafka
deploy:
  env:
    # Env vars to connect to PostgreSQL DB
    - name: POSTGRESQL_DATABASE
      value: frdemo
    - name: POSTGRESQL_USER
      value: frdemo
    - name: POSTGRESQL_PASSWORD
      value: frdemo
    - name: POSTGRESQL_DATASOURCE
      value: FRDemoDS
    - name: POSTGRESQL_JNDI
      value: java:/FRDemoDS
    - name: POSTGRESQL_SERVICE_HOST
      value: frdemo-ds
    - name: POSTGRESQL_SERVICE_PORT
      value: "5432"
    - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_BOOTSTRAP_SERVERS
      value: frdemo-kafka:9092
    - name: MAPBOX_BASE_URL
      value: frmapbox-mock:9123
# any non-null value will disable jolokia
#    - name: AB_JOLOKIA_OFF
#      value: "true"
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
